import guideIcon from "../../../public/assets/icons/guide.svg"
import cloudImage from "../../../public/assets/icons/cloud.svg"

const ResourcesHubMenuApi = [
    {
        "id": 1,
        "CatagoryTitle": "Blogs",
        "heroImageSrc": "",
        "heroContentLink": "", 
        "Contents": [
            { 
                "id": 1, 
                "imageSrc": "",
                "videoSrcImage": "",
                "imageAlt": "icon", 
                "titleText": "Email migrations to Microsoft 365",
                "subText": "",
                "contentLink": "",
            },
            { 
                "id": 2, 
                "imageSrc": "",
                "videoSrcImage": "",
                "imageAlt": "icon", 
                "titleText": "IMAP to Microsoft 365",
                "subText": "",
                "contentLink": "",
            },
            { 
                "id": 3,
                "imageSrc": "",
                "videoSrcImage": "",
                "imageAlt": "icon", 
                "titleText": "Exchange Server Hybrid Deployment",
                "subText": "",
                "contentLink": "",
            },
            { 
                "id": 4,
                "imageSrc": "",
                "videoSrcImage": "",
                "imageAlt": "icon", 
                "titleText": "Google to Microsoft 365",
                "subText": "",
                "contentLink": "",
            },
        ],
    },
    {
        "id": 2,
        "CatagoryTitle": "Technical Guides",
        "heroImageSrc": "https://document360.com/wp-content/uploads/2022/01/Ultimate-guide-to-writing-instructions-for-a-user-manual-Document360.png",
        "heroContentLink": "", 
        "Contents": [
            { 
                "id": 1,
                "imageSrc": guideIcon.src,
                "videoSrcImage": "",
                "imageAlt": "icon", 
                "titleText": "Cloud Migrations 2024 edition",
                "subText": "",
                "contentLink": "",
            },
        ],
    },
    {
        "id": 3,
        "CatagoryTitle": "Videos",
        "heroImageSrc": "",
        "heroContentLink": "",
        "Contents": [
            { 
                "id": 1,
                "imageSrc": "",
                "videoSrcImage": "https://i.ytimg.com/vi/VDiSgstbR0k/hq720.jpg",
                "imageAlt": "icon", 
                "titleText": "Windows System Administartor",
                "subText": "",
                "contentLink": "",
            },
            { 
                "id": 2, 
                "imageSrc": "",
                "videoSrcImage": "https://i.ytimg.com/vi/YZhdN1oSChk/hq720.jpg",
                "imageAlt": "icon", 
                "titleText": "Microsoft 365 Technial Support Specialist",
                "subText": "",
                "contentLink": "",
            },
            { 
                "id": 3, 
                "imageSrc": "",
                "videoSrcImage": "https://i.ytimg.com/vi/QCe4FRafUMs/hqdefault.jpg",
                "imageAlt": "icon", 
                "titleText": "Azure Active Directory (AD)",
                "subText": "",
                "contentLink": "",
            },
            { 
                "id": 4, 
                "imageSrc": "",
                "videoSrcImage": "https://i.ytimg.com/vi/EAbjPbwjh80/hq720.jpg",
                "imageAlt": "icon", 
                "titleText": "Helpdesk And Service Desk IT Technician",
                "subText": "",
                "contentLink": "",
            },
            { 
                "id": 5, 
                "imageSrc": "",
                "videoSrcImage": "https://i.ytimg.com/vi/FVfFMMtsD3g/hq720.jpg",
                "imageAlt": "icon", 
                "titleText": "Customer Service Representative",
                "subText": "",
                "contentLink": "",
            },
        ],
    },
    {
        "id": 4,
        "CatagoryTitle": "Case Studies",
        "heroImageSrc": "",
        "heroContentLink": "",
        "Contents": [
            { 
                "id": 1, 
                "imageSrc": cloudImage.src,
                "videoSrcImage": "",
                "imageAlt": "icon", 
                "titleText": "Cloud",
                "subText": "",
                "contentLink": "",
            },
        ],
    },
    {
        "id": 5,
        "CatagoryTitle": "Press & Media",
        "heroImageSrc": "",
        "heroContentLink": "",
        "Contents": [
            { 
                "id": 1, 
                "imageSrc": "",
                "videoSrcImage": "",
                "imageAlt": "Microsoft", 
                "titleText": "",
                "subText": "",
                "contentLink": "",
            },
            { 
                "id": 2, 
                "imageSrc": "",
                "videoSrcImage": "",
                "imageAlt": "Google", 
                "titleText": "",
                "subText": "",
                "contentLink": "",
            },
        ],
    },
];

export default ResourcesHubMenuApi; 