const TestimonialsApi = [
    {
        id: 1,
        linkAuthorProfile: "https://www.linkedin.com/in/thammaiah/",
        imageAuthor: "assets/images/people/thammu.jpg",
        testimonialAuthor: "Thammaiah",
        testimonialAuthorRole: "Sr. Product Manager",
        testimonialText: "I worked with Karan for over 4 years. He was one of my go to designers and managers when projects got difficult and client expectations needed to be managed. Where Karan truly stands out is his ability to prioritize client needs and ensure that outcomes match expectations. A specific project that I want to highlight is Hukoomi - the e-Services portal for the Govt of Qatar. Karan was on location for over 4 months while I supported the project mostly offshore. During the times that I wasn't around Karan managed communication and presentations for the entire design team and managed to build relationships that continue to payoff till date. As a design manager he mentors people to balance design needs and creative satisfaction with business needs and stakeholder goals. Additionally in his role of Business Development, Karan has played a large role in mobilizing projects from the Middle East region and ensuring that they are delivered right as well.",
        imageCompany: "assets/logos/adobe.svg", 
    },
    {
        id: 2,
        linkAuthorProfile: "https://www.linkedin.com/in/ruchi-bhatia-39a078113/",
        imageAuthor: "assets/images/people/Ruchi.jpg",
        testimonialAuthor: "Ruchi Bhatia",
        testimonialAuthorRole: "UX Researcher",
        testimonialText: "Karan's mentorship helped me face the roadblocks in my first design project with so much ease. He is highly skilled as a leader and also very efficiently brings his inputs from various disciplines to the design project, which is very important to holistically solve the design problem. His enthusiasm and motivation to tend things to succesful closure is exuberant. Working with Karan was a great learning experience :)",
        imageCompany: "assets/logos/Google.svg", 
    },
    {
        id: 3,
        linkAuthorProfile: "https://www.linkedin.com/in/najimussa/",
        imageAuthor: "assets/images/people/naji.jpg",
        testimonialAuthor: "Naji Musa",
        testimonialAuthorRole: "Digital Transformation Leader",
        testimonialText: "I have worked with Karran on two different mega projects where he led a team of UX/UI consultants and he delivered outstanding results. Karran is one of the most creative designers I have ever met. He is poised, intelligent, creative, genial, result-oriented, customer-centric and absolutely well-liked by his colleagues, superiors and most importantly his customers. I had definitely work with Karran if I get the opportunity again in the future.",
        imageCompany: "assets/logos/ministry.jpeg", 
    },
    {
        id: 4,
        linkAuthorProfile: "https://www.linkedin.com/in/najimussa/",
        imageAuthor: "assets/images/people/eric.jpg",
        testimonialAuthor: "Eric Jacob",
        testimonialAuthorRole: "Digital Marketing Manager",
        testimonialText: "Karran comes across soft spoken and reserved but that is only because he is always listening, formulating and piecing together the bigger picture when a group tends to lose sight of it. He is a master of his craft and helps guide his clients to an end result that they didnt know they wanted :) I had the pleasure of working closely with Karran on a project which was extremely tight on timelines and required a team that could pick things up and start running out of the gate. The delivery surpassed our expectations and he made sure that he and his team were diligent and thorough through the process. Hope to work with him again in the future.",
        imageCompany: "assets/logos/rakbank-color.svg", 
    },
    {
        id: 5,
        linkAuthorProfile: "https://www.linkedin.com/in/ravidaparthi/",
        imageAuthor: "assets/images/people/ravi.jpg",
        testimonialAuthor: "Ravi Daparthi",
        testimonialAuthorRole: "Chief Product Officer",
        testimonialText: "One of the easiest things in product space is dreaming an idea, we get hundreds every day and one of the toughest is to translate it to a visual shape. UX/UI is not about the placement of the controls, choosing the colors and creating interactions all the time. You need to have a hawk's eye on all aspects, Domain, Culture, Region of people using it, Command on basics, Discipline in delivery, ability to say NO as needed. Haymkarran perfectly fits the bill. You rarely finds his kind of breed in design teams. He is dedicated and goal oriented strategist that cannot be overestimated.We engaged him to reengineer the entire product UX, he made it look so simple with his exceptional customer obsessed mindset yet keeping the best practices in place. He mastered the art of balancing the both. His exceptional work flows, skills, ingenuity and understanding of change requests made the project a dream. Experiencing his fast and sharp mind at work is most remarkable. An absolutely phenomenal personality and every moment is a new learning experience working with him. If you wish to hire his consulting services, thats the best decision in your UX/UI engagements. Wishing all the best. You go heights boy.",
        imageCompany: "assets/logos/oorwin-original-green.svg", 
    },
    {
        id: 6,
        linkAuthorProfile: "https://www.linkedin.com/in/ravidaparthi/",
        imageAuthor: "assets/images/people/isha.jpg",
        testimonialAuthor: "Isha Khanolkar",
        testimonialAuthorRole: "Marketing Manager",
        testimonialText: "I had the opportunity to work with Karan on a project for The Organic World . In what seemed to be a complex project with varied expectations from multiple stakeholders , Karan was able to hold his own in managing the expectations and going beyond . His skill for articulating an argument for design and understanding and translating requirements to functions is truly remarkable . His gentle and childlike enthusiasm to challenge the brand to move to the next level is also very invigorating. We had a lot of fun working together with Lollypop on this project and we are extremely grateful to have had Karan to lead it .",
        imageCompany: "assets/logos/tow-color.svg", 
    },
    {
        id: 7,
        linkAuthorProfile: "https://www.linkedin.com/in/vishwapriya-manjunath-cspo-prince2-practitioner-09a94a130/",
        imageAuthor: "assets/images/people/vishwapriya.jpg",
        testimonialAuthor: "Vishwapriya Manjunath",
        testimonialAuthorRole: "Product Manager",
        testimonialText: "Haymkarran assisted us in one of our UI UX requirements. He got in brilliant idea related to AI and was swift in his actions in completing the project on agreed Timeliness. It was critical project, he and his team support was commendable. Thank you for all your work and assistance. YOU are one among The Best.",
        imageCompany: "assets/logos/emaar-color.svg", 
    },
    {
        id: 8,
        linkAuthorProfile: "https://www.linkedin.com/in/praveen-chintamani-1956885/",
        imageAuthor: "assets/images/people/praveen.jpg",
        testimonialAuthor: "Praveen Chintamani",
        testimonialAuthorRole: "Group Development Manager",
        testimonialText: "UX is not easy but can be made easy when you have power-packed talent like Haymkarran. Karran provides UX ability also includes in giving the solution not just Xperience. In simple words, he is the one best modern UX guy who can provide convenience for enterprise users and make enterprise apps a lot more friendly.",
        imageCompany: "assets/logos/intuit.svg", 
    },
    {
        id: 9,
        linkAuthorProfile: "https://www.linkedin.com/in/praveen-chintamani-1956885/",
        imageAuthor: "assets/images/people/dhilip.jpg",
        testimonialAuthor: "Dhilip Kumar",
        testimonialAuthorRole: "Lead Product Designer",
        testimonialText: "Dedication. That's the word that immediately comes to my mind, talking about Haymkarran. I have worked with him closely on a few projects at Lollypop design studio. I have loved the way he puts his soul and heart into the work he does. He is very much organized, knowledgeable, and eager to learn new things. Another practice he does, that resembles my habit, is the preparation he does. He would research and put a lot of effort into preparing before any meeting, project kick-off, client meeting, or even the regular work. As a peer worker, he volunteers himself to support and help others. That shows the leadership trait in him. In terms of business and UX, he keeps upgrading himself with knowledge and he applies various UX techniques to find design solutions for the right problem statements. I am sure he will reach more heights for his humbleness and studious hard work. He would be a great asset to the companies and I would highly recommend him. I wish him all the best and more success in his career and life.",
        imageCompany: "assets/logos/Mindvalley.svg", 
    },
];

export default TestimonialsApi;